//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace BLL
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class SiteMapEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“SiteMapEntities”部分中的连接字符串初始化新 SiteMapEntities 对象。
        /// </summary>
        public SiteMapEntities() : base("name=SiteMapEntities", "SiteMapEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 SiteMapEntities 对象。
        /// </summary>
        public SiteMapEntities(string connectionString) : base(connectionString, "SiteMapEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 SiteMapEntities 对象。
        /// </summary>
        public SiteMapEntities(EntityConnection connection) : base(connection, "SiteMapEntities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<SiteMapInfo> SiteMapInfos
        {
            get
            {
                if ((_SiteMapInfos == null))
                {
                    _SiteMapInfos = base.CreateObjectSet<SiteMapInfo>("SiteMapInfos");
                }
                return _SiteMapInfos;
            }
        }
        private ObjectSet<SiteMapInfo> _SiteMapInfos;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 SiteMapInfos EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSiteMapInfos(SiteMapInfo siteMapInfo)
        {
            base.AddObject("SiteMapInfos", siteMapInfo);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BBICMS.BLL", Name="SiteMapInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SiteMapInfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 SiteMapInfo 对象。
        /// </summary>
        /// <param name="siteMapId">SiteMapId 属性的初始值。</param>
        /// <param name="uRL">URL 属性的初始值。</param>
        /// <param name="realURL">RealURL 属性的初始值。</param>
        /// <param name="title">Title 属性的初始值。</param>
        /// <param name="keywords">Keywords 属性的初始值。</param>
        /// <param name="description">Description 属性的初始值。</param>
        /// <param name="parent">Parent 属性的初始值。</param>
        /// <param name="uRLId">URLId 属性的初始值。</param>
        /// <param name="nodeType">NodeType 属性的初始值。</param>
        /// <param name="sortOrder">SortOrder 属性的初始值。</param>
        /// <param name="active">Active 属性的初始值。</param>
        /// <param name="dateAdded">DateAdded 属性的初始值。</param>
        /// <param name="addedBy">AddedBy 属性的初始值。</param>
        /// <param name="dateUpdated">DateUpdated 属性的初始值。</param>
        /// <param name="updatedBy">UpdatedBy 属性的初始值。</param>
        public static SiteMapInfo CreateSiteMapInfo(global::System.Int32 siteMapId, global::System.String uRL, global::System.String realURL, global::System.String title, global::System.String keywords, global::System.String description, global::System.Int32 parent, global::System.Int32 uRLId, global::System.Int32 nodeType, global::System.Int32 sortOrder, global::System.Boolean active, global::System.DateTime dateAdded, global::System.String addedBy, global::System.DateTime dateUpdated, global::System.String updatedBy)
        {
            SiteMapInfo siteMapInfo = new SiteMapInfo();
            siteMapInfo.SiteMapId = siteMapId;
            siteMapInfo.URL = uRL;
            siteMapInfo.RealURL = realURL;
            siteMapInfo.Title = title;
            siteMapInfo.Keywords = keywords;
            siteMapInfo.Description = description;
            siteMapInfo.Parent = parent;
            siteMapInfo.URLId = uRLId;
            siteMapInfo.NodeType = nodeType;
            siteMapInfo.SortOrder = sortOrder;
            siteMapInfo.Active = active;
            siteMapInfo.DateAdded = dateAdded;
            siteMapInfo.AddedBy = addedBy;
            siteMapInfo.DateUpdated = dateUpdated;
            siteMapInfo.UpdatedBy = updatedBy;
            return siteMapInfo;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SiteMapId
        {
            get
            {
                return _SiteMapId;
            }
            set
            {
                if (_SiteMapId != value)
                {
                    OnSiteMapIdChanging(value);
                    ReportPropertyChanging("SiteMapId");
                    _SiteMapId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SiteMapId");
                    OnSiteMapIdChanged();
                }
            }
        }
        private global::System.Int32 _SiteMapId;
        partial void OnSiteMapIdChanging(global::System.Int32 value);
        partial void OnSiteMapIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String URL
        {
            get
            {
                return _URL;
            }
            set
            {
                OnURLChanging(value);
                ReportPropertyChanging("URL");
                _URL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("URL");
                OnURLChanged();
            }
        }
        private global::System.String _URL;
        partial void OnURLChanging(global::System.String value);
        partial void OnURLChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RealURL
        {
            get
            {
                return _RealURL;
            }
            set
            {
                OnRealURLChanging(value);
                ReportPropertyChanging("RealURL");
                _RealURL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RealURL");
                OnRealURLChanged();
            }
        }
        private global::System.String _RealURL;
        partial void OnRealURLChanging(global::System.String value);
        partial void OnRealURLChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Keywords
        {
            get
            {
                return _Keywords;
            }
            set
            {
                OnKeywordsChanging(value);
                ReportPropertyChanging("Keywords");
                _Keywords = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Keywords");
                OnKeywordsChanged();
            }
        }
        private global::System.String _Keywords;
        partial void OnKeywordsChanging(global::System.String value);
        partial void OnKeywordsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Roles
        {
            get
            {
                return _Roles;
            }
            set
            {
                OnRolesChanging(value);
                ReportPropertyChanging("Roles");
                _Roles = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Roles");
                OnRolesChanged();
            }
        }
        private global::System.String _Roles;
        partial void OnRolesChanging(global::System.String value);
        partial void OnRolesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Parent
        {
            get
            {
                return _Parent;
            }
            set
            {
                OnParentChanging(value);
                ReportPropertyChanging("Parent");
                _Parent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Parent");
                OnParentChanged();
            }
        }
        private global::System.Int32 _Parent;
        partial void OnParentChanging(global::System.Int32 value);
        partial void OnParentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 URLId
        {
            get
            {
                return _URLId;
            }
            set
            {
                OnURLIdChanging(value);
                ReportPropertyChanging("URLId");
                _URLId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("URLId");
                OnURLIdChanged();
            }
        }
        private global::System.Int32 _URLId;
        partial void OnURLIdChanging(global::System.Int32 value);
        partial void OnURLIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String URLType
        {
            get
            {
                return _URLType;
            }
            set
            {
                OnURLTypeChanging(value);
                ReportPropertyChanging("URLType");
                _URLType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("URLType");
                OnURLTypeChanged();
            }
        }
        private global::System.String _URLType;
        partial void OnURLTypeChanging(global::System.String value);
        partial void OnURLTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NodeType
        {
            get
            {
                return _NodeType;
            }
            set
            {
                OnNodeTypeChanging(value);
                ReportPropertyChanging("NodeType");
                _NodeType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NodeType");
                OnNodeTypeChanged();
            }
        }
        private global::System.Int32 _NodeType;
        partial void OnNodeTypeChanging(global::System.Int32 value);
        partial void OnNodeTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SortOrder
        {
            get
            {
                return _SortOrder;
            }
            set
            {
                OnSortOrderChanging(value);
                ReportPropertyChanging("SortOrder");
                _SortOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SortOrder");
                OnSortOrderChanged();
            }
        }
        private global::System.Int32 _SortOrder;
        partial void OnSortOrderChanging(global::System.Int32 value);
        partial void OnSortOrderChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateAdded
        {
            get
            {
                return _DateAdded;
            }
            set
            {
                OnDateAddedChanging(value);
                ReportPropertyChanging("DateAdded");
                _DateAdded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateAdded");
                OnDateAddedChanged();
            }
        }
        private global::System.DateTime _DateAdded;
        partial void OnDateAddedChanging(global::System.DateTime value);
        partial void OnDateAddedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddedBy
        {
            get
            {
                return _AddedBy;
            }
            set
            {
                OnAddedByChanging(value);
                ReportPropertyChanging("AddedBy");
                _AddedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AddedBy");
                OnAddedByChanged();
            }
        }
        private global::System.String _AddedBy;
        partial void OnAddedByChanging(global::System.String value);
        partial void OnAddedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateUpdated
        {
            get
            {
                return _DateUpdated;
            }
            set
            {
                OnDateUpdatedChanging(value);
                ReportPropertyChanging("DateUpdated");
                _DateUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateUpdated");
                OnDateUpdatedChanged();
            }
        }
        private global::System.DateTime _DateUpdated;
        partial void OnDateUpdatedChanging(global::System.DateTime value);
        partial void OnDateUpdatedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private global::System.String _UpdatedBy;
        partial void OnUpdatedByChanging(global::System.String value);
        partial void OnUpdatedByChanged();

        #endregion

    
    }

    #endregion

    
}
