// Assembly TBHBLL, Version 3.5.0.1

[assembly: System.Reflection.AssemblyVersion("3.5.0.1")]
[assembly: System.Data.Objects.DataClasses.EdmSchema("9b855b48-8569-4238-b534-0fb5a3aba2dd")]
[assembly: System.Data.Objects.DataClasses.EdmSchema("cd44a599-a076-4fdb-9902-3f075743b42b")]
[assembly: System.Data.Objects.DataClasses.EdmRelationship("ShoppingCart", "FK_tbh_OrderItems_tbh_Orders", "tbh_Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TheBeerHouse.BLL.Store.Order), "tbh_OrderItems", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TheBeerHouse.BLL.Store.OrderItem))]
[assembly: System.Data.Objects.DataClasses.EdmSchema("a7fd92e9-acc6-40ae-9450-8119671cb55c")]
[assembly: System.Web.UI.WebResource("LocalizingResources.Validation.js", "text/javascript")]
[assembly: System.Data.Objects.DataClasses.EdmSchema("6446919b-83bb-4334-ad97-0338ca689318")]
[assembly: System.Data.Objects.DataClasses.EdmRelationship("TheBeerHousePolling", "FK_tbh_PollOptions_tbh_Polls", "tbh_Polls", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TheBeerHouse.BLL.Poll), "tbh_PollOptions", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TheBeerHouse.BLL.PollOption))]
[assembly: System.Data.Objects.DataClasses.EdmRelationship("ShoppingCart", "FK_tbh_Products_tbh_Departments", "tbh_Departments", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TheBeerHouse.BLL.Store.Department), "tbh_Products", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TheBeerHouse.BLL.Store.Product))]
[assembly: System.Data.Objects.DataClasses.EdmSchema("47bbe9cf-3bb9-4365-8571-cf924b718c8d")]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.DisableOptimizations | System.Diagnostics.DebuggableAttribute.DebuggingModes.EnableEditAndContinue | System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | System.Diagnostics.DebuggableAttribute.DebuggingModes.Default)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Runtime.CompilerServices.Extension]
[assembly: System.Reflection.AssemblyFileVersion("3.5.0.1")]
[assembly: System.Runtime.InteropServices.Guid("2189a190-9c56-42ad-ad49-7fbeb9c94fe9")]
[assembly: System.Web.UI.ScriptResource("LocalizingResources.Validation.js", "LocalizingResources.ValidationResources", "Validation")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 WROX 2008")]
[assembly: System.Reflection.AssemblyProduct("TBHBLL")]
[assembly: System.Reflection.AssemblyCompany("WROX")]
[assembly: System.Reflection.AssemblyDescription("")]
[assembly: System.Reflection.AssemblyTitle("The Beer House Class Library")]
[assembly: System.Data.Objects.DataClasses.EdmRelationship("ArticlesModel", "FK_tbh_Comments_tbh_Articles", "tbh_Articles", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TheBeerHouse.BLL.Articles.Article), "tbh_Comments", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TheBeerHouse.BLL.Articles.Comment))]
[assembly: System.Data.Objects.DataClasses.EdmRelationship("ArticlesModel", "FK_tbh_Articles_tbh_Categories", "tbh_Categories", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TheBeerHouse.BLL.Articles.Category), "tbh_Articles", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TheBeerHouse.BLL.Articles.Article))]
[assembly: System.Data.Objects.DataClasses.EdmSchema("f51cffee-e960-48e7-9c5b-25c2f9a09432")]
[assembly: System.Data.Objects.DataClasses.EdmRelationship("CalendarofEventsModel", "FK_EventRSVP_Event", "tbh_EventInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TheBeerHouse.BLL.EventCalendar.EventInfo), "tbh_EventRSVP", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TheBeerHouse.BLL.EventCalendar.EventRSVP))]
[assembly: System.Data.Objects.DataClasses.EdmSchema("28e57c03-9ed9-4c11-a455-59a43cb7c9ba")]
[assembly: System.Data.Objects.DataClasses.EdmRelationship("ForumsModel", "FK_tbh_Posts_tbh_Forums", "tbh_Forums", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TheBeerHouse.BLL.Forums.Forum), "tbh_Posts", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TheBeerHouse.BLL.Forums.Post))]
[assembly: System.Data.Objects.DataClasses.EdmSchema("f0095fbd-8123-454a-b9b0-7ec129de4e3b")]
[assembly: System.Data.Objects.DataClasses.EdmRelationship("TheBeerHouseVBModel", "FK_Pictures_Album", "tbh_Album", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(TheBeerHouse.BLL.Gallery.Album), "tbh_Pictures", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(TheBeerHouse.BLL.Gallery.Picture))]

