//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("BBICMS.Events", "FK_EventRSVP_Event", "tbh_EventInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BBICMS.Events.EventInfo), "tbh_EventRSVP", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BBICMS.Events.EventRSVP))]

#endregion

namespace BBICMS.Events
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class CalendarofEventsEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“CalendarofEventsEntities”部分中的连接字符串初始化新 CalendarofEventsEntities 对象。
        /// </summary>
        public CalendarofEventsEntities() : base("name=CalendarofEventsEntities", "CalendarofEventsEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 CalendarofEventsEntities 对象。
        /// </summary>
        public CalendarofEventsEntities(string connectionString) : base(connectionString, "CalendarofEventsEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 CalendarofEventsEntities 对象。
        /// </summary>
        public CalendarofEventsEntities(EntityConnection connection) : base(connection, "CalendarofEventsEntities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<EventInfo> EventInfos
        {
            get
            {
                if ((_EventInfos == null))
                {
                    _EventInfos = base.CreateObjectSet<EventInfo>("EventInfos");
                }
                return _EventInfos;
            }
        }
        private ObjectSet<EventInfo> _EventInfos;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<EventRSVP> EventRSVPs
        {
            get
            {
                if ((_EventRSVPs == null))
                {
                    _EventRSVPs = base.CreateObjectSet<EventRSVP>("EventRSVPs");
                }
                return _EventRSVPs;
            }
        }
        private ObjectSet<EventRSVP> _EventRSVPs;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 EventInfos EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToEventInfos(EventInfo eventInfo)
        {
            base.AddObject("EventInfos", eventInfo);
        }
    
        /// <summary>
        /// 用于向 EventRSVPs EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToEventRSVPs(EventRSVP eventRSVP)
        {
            base.AddObject("EventRSVPs", eventRSVP);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BBICMS.Events", Name="EventInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EventInfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 EventInfo 对象。
        /// </summary>
        /// <param name="eventId">EventId 属性的初始值。</param>
        /// <param name="eventTitle">EventTitle 属性的初始值。</param>
        /// <param name="eventDesc">EventDesc 属性的初始值。</param>
        /// <param name="eventDate">EventDate 属性的初始值。</param>
        /// <param name="eventExpires">EventExpires 属性的初始值。</param>
        /// <param name="eventTime">EventTime 属性的初始值。</param>
        /// <param name="importance">Importance 属性的初始值。</param>
        /// <param name="allowRegistration">AllowRegistration 属性的初始值。</param>
        /// <param name="active">Active 属性的初始值。</param>
        /// <param name="addedBy">AddedBy 属性的初始值。</param>
        /// <param name="dateAdded">DateAdded 属性的初始值。</param>
        /// <param name="updatedBy">UpdatedBy 属性的初始值。</param>
        /// <param name="dateUpdated">DateUpdated 属性的初始值。</param>
        public static EventInfo CreateEventInfo(global::System.Int32 eventId, global::System.String eventTitle, global::System.String eventDesc, global::System.DateTime eventDate, global::System.DateTime eventExpires, global::System.String eventTime, global::System.Int32 importance, global::System.Boolean allowRegistration, global::System.Boolean active, global::System.String addedBy, global::System.DateTime dateAdded, global::System.String updatedBy, global::System.DateTime dateUpdated)
        {
            EventInfo eventInfo = new EventInfo();
            eventInfo.EventId = eventId;
            eventInfo.EventTitle = eventTitle;
            eventInfo.EventDesc = eventDesc;
            eventInfo.EventDate = eventDate;
            eventInfo.EventExpires = eventExpires;
            eventInfo.EventTime = eventTime;
            eventInfo.Importance = importance;
            eventInfo.AllowRegistration = allowRegistration;
            eventInfo.Active = active;
            eventInfo.AddedBy = addedBy;
            eventInfo.DateAdded = dateAdded;
            eventInfo.UpdatedBy = updatedBy;
            eventInfo.DateUpdated = dateUpdated;
            return eventInfo;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EventId
        {
            get
            {
                return _EventId;
            }
            set
            {
                if (_EventId != value)
                {
                    OnEventIdChanging(value);
                    ReportPropertyChanging("EventId");
                    _EventId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EventId");
                    OnEventIdChanged();
                }
            }
        }
        private global::System.Int32 _EventId;
        partial void OnEventIdChanging(global::System.Int32 value);
        partial void OnEventIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EventTitle
        {
            get
            {
                return _EventTitle;
            }
            set
            {
                OnEventTitleChanging(value);
                ReportPropertyChanging("EventTitle");
                _EventTitle = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EventTitle");
                OnEventTitleChanged();
            }
        }
        private global::System.String _EventTitle;
        partial void OnEventTitleChanging(global::System.String value);
        partial void OnEventTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EventDesc
        {
            get
            {
                return _EventDesc;
            }
            set
            {
                OnEventDescChanging(value);
                ReportPropertyChanging("EventDesc");
                _EventDesc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EventDesc");
                OnEventDescChanged();
            }
        }
        private global::System.String _EventDesc;
        partial void OnEventDescChanging(global::System.String value);
        partial void OnEventDescChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EventDate
        {
            get
            {
                return _EventDate;
            }
            set
            {
                OnEventDateChanging(value);
                ReportPropertyChanging("EventDate");
                _EventDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EventDate");
                OnEventDateChanged();
            }
        }
        private global::System.DateTime _EventDate;
        partial void OnEventDateChanging(global::System.DateTime value);
        partial void OnEventDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EventEndDate
        {
            get
            {
                return _EventEndDate;
            }
            set
            {
                OnEventEndDateChanging(value);
                ReportPropertyChanging("EventEndDate");
                _EventEndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EventEndDate");
                OnEventEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EventEndDate;
        partial void OnEventEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEventEndDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EventExpires
        {
            get
            {
                return _EventExpires;
            }
            set
            {
                OnEventExpiresChanging(value);
                ReportPropertyChanging("EventExpires");
                _EventExpires = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EventExpires");
                OnEventExpiresChanged();
            }
        }
        private global::System.DateTime _EventExpires;
        partial void OnEventExpiresChanging(global::System.DateTime value);
        partial void OnEventExpiresChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EventTime
        {
            get
            {
                return _EventTime;
            }
            set
            {
                OnEventTimeChanging(value);
                ReportPropertyChanging("EventTime");
                _EventTime = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EventTime");
                OnEventTimeChanged();
            }
        }
        private global::System.String _EventTime;
        partial void OnEventTimeChanging(global::System.String value);
        partial void OnEventTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                OnEndTimeChanging(value);
                ReportPropertyChanging("EndTime");
                _EndTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EndTime");
                OnEndTimeChanged();
            }
        }
        private global::System.String _EndTime;
        partial void OnEndTimeChanging(global::System.String value);
        partial void OnEndTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EventLocation
        {
            get
            {
                return _EventLocation;
            }
            set
            {
                OnEventLocationChanging(value);
                ReportPropertyChanging("EventLocation");
                _EventLocation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EventLocation");
                OnEventLocationChanged();
            }
        }
        private global::System.String _EventLocation;
        partial void OnEventLocationChanging(global::System.String value);
        partial void OnEventLocationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZipCode
        {
            get
            {
                return _ZipCode;
            }
            set
            {
                OnZipCodeChanging(value);
                ReportPropertyChanging("ZipCode");
                _ZipCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZipCode");
                OnZipCodeChanged();
            }
        }
        private global::System.String _ZipCode;
        partial void OnZipCodeChanging(global::System.String value);
        partial void OnZipCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Featured
        {
            get
            {
                return _Featured;
            }
            set
            {
                OnFeaturedChanging(value);
                ReportPropertyChanging("Featured");
                _Featured = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Featured");
                OnFeaturedChanged();
            }
        }
        private Nullable<global::System.Boolean> _Featured;
        partial void OnFeaturedChanging(Nullable<global::System.Boolean> value);
        partial void OnFeaturedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Duration
        {
            get
            {
                return _Duration;
            }
            set
            {
                OnDurationChanging(value);
                ReportPropertyChanging("Duration");
                _Duration = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Duration");
                OnDurationChanged();
            }
        }
        private global::System.String _Duration;
        partial void OnDurationChanging(global::System.String value);
        partial void OnDurationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Importance
        {
            get
            {
                return _Importance;
            }
            set
            {
                OnImportanceChanging(value);
                ReportPropertyChanging("Importance");
                _Importance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Importance");
                OnImportanceChanged();
            }
        }
        private global::System.Int32 _Importance;
        partial void OnImportanceChanging(global::System.Int32 value);
        partial void OnImportanceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean AllowRegistration
        {
            get
            {
                return _AllowRegistration;
            }
            set
            {
                OnAllowRegistrationChanging(value);
                ReportPropertyChanging("AllowRegistration");
                _AllowRegistration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AllowRegistration");
                OnAllowRegistrationChanged();
            }
        }
        private global::System.Boolean _AllowRegistration;
        partial void OnAllowRegistrationChanging(global::System.Boolean value);
        partial void OnAllowRegistrationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Attachment
        {
            get
            {
                return _Attachment;
            }
            set
            {
                OnAttachmentChanging(value);
                ReportPropertyChanging("Attachment");
                _Attachment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Attachment");
                OnAttachmentChanged();
            }
        }
        private global::System.String _Attachment;
        partial void OnAttachmentChanging(global::System.String value);
        partial void OnAttachmentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddedBy
        {
            get
            {
                return _AddedBy;
            }
            set
            {
                OnAddedByChanging(value);
                ReportPropertyChanging("AddedBy");
                _AddedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AddedBy");
                OnAddedByChanged();
            }
        }
        private global::System.String _AddedBy;
        partial void OnAddedByChanging(global::System.String value);
        partial void OnAddedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateAdded
        {
            get
            {
                return _DateAdded;
            }
            set
            {
                OnDateAddedChanging(value);
                ReportPropertyChanging("DateAdded");
                _DateAdded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateAdded");
                OnDateAddedChanged();
            }
        }
        private global::System.DateTime _DateAdded;
        partial void OnDateAddedChanging(global::System.DateTime value);
        partial void OnDateAddedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private global::System.String _UpdatedBy;
        partial void OnUpdatedByChanging(global::System.String value);
        partial void OnUpdatedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateUpdated
        {
            get
            {
                return _DateUpdated;
            }
            set
            {
                OnDateUpdatedChanging(value);
                ReportPropertyChanging("DateUpdated");
                _DateUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateUpdated");
                OnDateUpdatedChanged();
            }
        }
        private global::System.DateTime _DateUpdated;
        partial void OnDateUpdatedChanging(global::System.DateTime value);
        partial void OnDateUpdatedChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BBICMS.Events", "FK_EventRSVP_Event", "tbh_EventRSVP")]
        public EntityCollection<EventRSVP> EventRSVPs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EventRSVP>("BBICMS.Events.FK_EventRSVP_Event", "tbh_EventRSVP");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EventRSVP>("BBICMS.Events.FK_EventRSVP_Event", "tbh_EventRSVP", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BBICMS.Events", Name="EventRSVP")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EventRSVP : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 EventRSVP 对象。
        /// </summary>
        /// <param name="eventRSVPId">EventRSVPId 属性的初始值。</param>
        /// <param name="firstName">FirstName 属性的初始值。</param>
        /// <param name="lastName">LastName 属性的初始值。</param>
        /// <param name="noGuests">NoGuests 属性的初始值。</param>
        /// <param name="attendStatus">AttendStatus 属性的初始值。</param>
        /// <param name="active">Active 属性的初始值。</param>
        /// <param name="dateAdded">DateAdded 属性的初始值。</param>
        /// <param name="addedBy">AddedBy 属性的初始值。</param>
        /// <param name="dateUpdated">DateUpdated 属性的初始值。</param>
        /// <param name="updatedBy">UpdatedBy 属性的初始值。</param>
        public static EventRSVP CreateEventRSVP(global::System.Int32 eventRSVPId, global::System.String firstName, global::System.String lastName, global::System.Int32 noGuests, global::System.Int32 attendStatus, global::System.Boolean active, global::System.DateTime dateAdded, global::System.String addedBy, global::System.DateTime dateUpdated, global::System.String updatedBy)
        {
            EventRSVP eventRSVP = new EventRSVP();
            eventRSVP.EventRSVPId = eventRSVPId;
            eventRSVP.FirstName = firstName;
            eventRSVP.LastName = lastName;
            eventRSVP.NoGuests = noGuests;
            eventRSVP.AttendStatus = attendStatus;
            eventRSVP.Active = active;
            eventRSVP.DateAdded = dateAdded;
            eventRSVP.AddedBy = addedBy;
            eventRSVP.DateUpdated = dateUpdated;
            eventRSVP.UpdatedBy = updatedBy;
            return eventRSVP;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EventRSVPId
        {
            get
            {
                return _EventRSVPId;
            }
            set
            {
                if (_EventRSVPId != value)
                {
                    OnEventRSVPIdChanging(value);
                    ReportPropertyChanging("EventRSVPId");
                    _EventRSVPId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EventRSVPId");
                    OnEventRSVPIdChanged();
                }
            }
        }
        private global::System.Int32 _EventRSVPId;
        partial void OnEventRSVPIdChanging(global::System.Int32 value);
        partial void OnEventRSVPIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Organization
        {
            get
            {
                return _Organization;
            }
            set
            {
                OnOrganizationChanging(value);
                ReportPropertyChanging("Organization");
                _Organization = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Organization");
                OnOrganizationChanged();
            }
        }
        private global::System.String _Organization;
        partial void OnOrganizationChanging(global::System.String value);
        partial void OnOrganizationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String JobTitle
        {
            get
            {
                return _JobTitle;
            }
            set
            {
                OnJobTitleChanging(value);
                ReportPropertyChanging("JobTitle");
                _JobTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("JobTitle");
                OnJobTitleChanged();
            }
        }
        private global::System.String _JobTitle;
        partial void OnJobTitleChanging(global::System.String value);
        partial void OnJobTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EMail
        {
            get
            {
                return _EMail;
            }
            set
            {
                OnEMailChanging(value);
                ReportPropertyChanging("EMail");
                _EMail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EMail");
                OnEMailChanged();
            }
        }
        private global::System.String _EMail;
        partial void OnEMailChanging(global::System.String value);
        partial void OnEMailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NoGuests
        {
            get
            {
                return _NoGuests;
            }
            set
            {
                OnNoGuestsChanging(value);
                ReportPropertyChanging("NoGuests");
                _NoGuests = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NoGuests");
                OnNoGuestsChanged();
            }
        }
        private global::System.Int32 _NoGuests;
        partial void OnNoGuestsChanging(global::System.Int32 value);
        partial void OnNoGuestsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GuestNames
        {
            get
            {
                return _GuestNames;
            }
            set
            {
                OnGuestNamesChanging(value);
                ReportPropertyChanging("GuestNames");
                _GuestNames = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GuestNames");
                OnGuestNamesChanged();
            }
        }
        private global::System.String _GuestNames;
        partial void OnGuestNamesChanging(global::System.String value);
        partial void OnGuestNamesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AttendStatus
        {
            get
            {
                return _AttendStatus;
            }
            set
            {
                OnAttendStatusChanging(value);
                ReportPropertyChanging("AttendStatus");
                _AttendStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AttendStatus");
                OnAttendStatusChanged();
            }
        }
        private global::System.Int32 _AttendStatus;
        partial void OnAttendStatusChanging(global::System.Int32 value);
        partial void OnAttendStatusChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateAdded
        {
            get
            {
                return _DateAdded;
            }
            set
            {
                OnDateAddedChanging(value);
                ReportPropertyChanging("DateAdded");
                _DateAdded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateAdded");
                OnDateAddedChanged();
            }
        }
        private global::System.DateTime _DateAdded;
        partial void OnDateAddedChanging(global::System.DateTime value);
        partial void OnDateAddedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddedBy
        {
            get
            {
                return _AddedBy;
            }
            set
            {
                OnAddedByChanging(value);
                ReportPropertyChanging("AddedBy");
                _AddedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AddedBy");
                OnAddedByChanged();
            }
        }
        private global::System.String _AddedBy;
        partial void OnAddedByChanging(global::System.String value);
        partial void OnAddedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateUpdated
        {
            get
            {
                return _DateUpdated;
            }
            set
            {
                OnDateUpdatedChanging(value);
                ReportPropertyChanging("DateUpdated");
                _DateUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateUpdated");
                OnDateUpdatedChanged();
            }
        }
        private global::System.DateTime _DateUpdated;
        partial void OnDateUpdatedChanging(global::System.DateTime value);
        partial void OnDateUpdatedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private global::System.String _UpdatedBy;
        partial void OnUpdatedByChanging(global::System.String value);
        partial void OnUpdatedByChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BBICMS.Events", "FK_EventRSVP_Event", "tbh_EventInfo")]
        public EventInfo EventInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EventInfo>("BBICMS.Events.FK_EventRSVP_Event", "tbh_EventInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EventInfo>("BBICMS.Events.FK_EventRSVP_Event", "tbh_EventInfo").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EventInfo> EventInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EventInfo>("BBICMS.Events.FK_EventRSVP_Event", "tbh_EventInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EventInfo>("BBICMS.Events.FK_EventRSVP_Event", "tbh_EventInfo", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
