//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("BBICMS.Forums", "FK_tbh_Posts_tbh_Forums", "tbh_Forums", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BBICMS.Forums.Forum), "tbh_Posts", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BBICMS.Forums.Post))]

#endregion

namespace BBICMS.Forums
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class ForumModel : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“ForumModel”部分中的连接字符串初始化新 ForumModel 对象。
        /// </summary>
        public ForumModel() : base("name=ForumModel", "ForumModel")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ForumModel 对象。
        /// </summary>
        public ForumModel(string connectionString) : base(connectionString, "ForumModel")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ForumModel 对象。
        /// </summary>
        public ForumModel(EntityConnection connection) : base(connection, "ForumModel")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Forum> Forums
        {
            get
            {
                if ((_Forums == null))
                {
                    _Forums = base.CreateObjectSet<Forum>("Forums");
                }
                return _Forums;
            }
        }
        private ObjectSet<Forum> _Forums;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Post> Posts
        {
            get
            {
                if ((_Posts == null))
                {
                    _Posts = base.CreateObjectSet<Post>("Posts");
                }
                return _Posts;
            }
        }
        private ObjectSet<Post> _Posts;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Forums EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToForums(Forum forum)
        {
            base.AddObject("Forums", forum);
        }
    
        /// <summary>
        /// 用于向 Posts EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToPosts(Post post)
        {
            base.AddObject("Posts", post);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BBICMS.Forums", Name="Forum")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Forum : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Forum 对象。
        /// </summary>
        /// <param name="forumID">ForumID 属性的初始值。</param>
        /// <param name="addedDate">AddedDate 属性的初始值。</param>
        /// <param name="addedBy">AddedBy 属性的初始值。</param>
        /// <param name="title">Title 属性的初始值。</param>
        /// <param name="moderated">Moderated 属性的初始值。</param>
        /// <param name="importance">Importance 属性的初始值。</param>
        /// <param name="updatedDate">UpdatedDate 属性的初始值。</param>
        /// <param name="active">Active 属性的初始值。</param>
        public static Forum CreateForum(global::System.Int32 forumID, global::System.DateTime addedDate, global::System.String addedBy, global::System.String title, global::System.Boolean moderated, global::System.Int32 importance, global::System.DateTime updatedDate, global::System.Boolean active)
        {
            Forum forum = new Forum();
            forum.ForumID = forumID;
            forum.AddedDate = addedDate;
            forum.AddedBy = addedBy;
            forum.Title = title;
            forum.Moderated = moderated;
            forum.Importance = importance;
            forum.UpdatedDate = updatedDate;
            forum.Active = active;
            return forum;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ForumID
        {
            get
            {
                return _ForumID;
            }
            set
            {
                if (_ForumID != value)
                {
                    OnForumIDChanging(value);
                    ReportPropertyChanging("ForumID");
                    _ForumID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ForumID");
                    OnForumIDChanged();
                }
            }
        }
        private global::System.Int32 _ForumID;
        partial void OnForumIDChanging(global::System.Int32 value);
        partial void OnForumIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AddedDate
        {
            get
            {
                return _AddedDate;
            }
            set
            {
                OnAddedDateChanging(value);
                ReportPropertyChanging("AddedDate");
                _AddedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedDate");
                OnAddedDateChanged();
            }
        }
        private global::System.DateTime _AddedDate;
        partial void OnAddedDateChanging(global::System.DateTime value);
        partial void OnAddedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddedBy
        {
            get
            {
                return _AddedBy;
            }
            set
            {
                OnAddedByChanging(value);
                ReportPropertyChanging("AddedBy");
                _AddedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AddedBy");
                OnAddedByChanged();
            }
        }
        private global::System.String _AddedBy;
        partial void OnAddedByChanging(global::System.String value);
        partial void OnAddedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Moderated
        {
            get
            {
                return _Moderated;
            }
            set
            {
                OnModeratedChanging(value);
                ReportPropertyChanging("Moderated");
                _Moderated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Moderated");
                OnModeratedChanged();
            }
        }
        private global::System.Boolean _Moderated;
        partial void OnModeratedChanging(global::System.Boolean value);
        partial void OnModeratedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Importance
        {
            get
            {
                return _Importance;
            }
            set
            {
                OnImportanceChanging(value);
                ReportPropertyChanging("Importance");
                _Importance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Importance");
                OnImportanceChanged();
            }
        }
        private global::System.Int32 _Importance;
        partial void OnImportanceChanging(global::System.Int32 value);
        partial void OnImportanceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageUrl
        {
            get
            {
                return _ImageUrl;
            }
            set
            {
                OnImageUrlChanging(value);
                ReportPropertyChanging("ImageUrl");
                _ImageUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImageUrl");
                OnImageUrlChanged();
            }
        }
        private global::System.String _ImageUrl;
        partial void OnImageUrlChanging(global::System.String value);
        partial void OnImageUrlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UpdatedDate
        {
            get
            {
                return _UpdatedDate;
            }
            set
            {
                OnUpdatedDateChanging(value);
                ReportPropertyChanging("UpdatedDate");
                _UpdatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedDate");
                OnUpdatedDateChanged();
            }
        }
        private global::System.DateTime _UpdatedDate;
        partial void OnUpdatedDateChanging(global::System.DateTime value);
        partial void OnUpdatedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private global::System.String _UpdatedBy;
        partial void OnUpdatedByChanging(global::System.String value);
        partial void OnUpdatedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BBICMS.Forums", "FK_tbh_Posts_tbh_Forums", "tbh_Posts")]
        public EntityCollection<Post> Posts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Post>("BBICMS.Forums.FK_tbh_Posts_tbh_Forums", "tbh_Posts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Post>("BBICMS.Forums.FK_tbh_Posts_tbh_Forums", "tbh_Posts", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BBICMS.Forums", Name="Post")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Post : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Post 对象。
        /// </summary>
        /// <param name="postID">PostID 属性的初始值。</param>
        /// <param name="addedDate">AddedDate 属性的初始值。</param>
        /// <param name="addedBy">AddedBy 属性的初始值。</param>
        /// <param name="addedByIP">AddedByIP 属性的初始值。</param>
        /// <param name="parentPostID">ParentPostID 属性的初始值。</param>
        /// <param name="title">Title 属性的初始值。</param>
        /// <param name="body">Body 属性的初始值。</param>
        /// <param name="approved">Approved 属性的初始值。</param>
        /// <param name="sticky">Sticky 属性的初始值。</param>
        /// <param name="closed">Closed 属性的初始值。</param>
        /// <param name="viewCount">ViewCount 属性的初始值。</param>
        /// <param name="replyCount">ReplyCount 属性的初始值。</param>
        /// <param name="lastPostBy">LastPostBy 属性的初始值。</param>
        /// <param name="lastPostDate">LastPostDate 属性的初始值。</param>
        /// <param name="updatedDate">UpdatedDate 属性的初始值。</param>
        /// <param name="active">Active 属性的初始值。</param>
        public static Post CreatePost(global::System.Int32 postID, global::System.DateTime addedDate, global::System.String addedBy, global::System.String addedByIP, global::System.Int32 parentPostID, global::System.String title, global::System.String body, global::System.Boolean approved, global::System.Boolean sticky, global::System.Boolean closed, global::System.Int32 viewCount, global::System.Int32 replyCount, global::System.String lastPostBy, global::System.DateTime lastPostDate, global::System.DateTime updatedDate, global::System.Boolean active)
        {
            Post post = new Post();
            post.PostID = postID;
            post.AddedDate = addedDate;
            post.AddedBy = addedBy;
            post.AddedByIP = addedByIP;
            post.ParentPostID = parentPostID;
            post.Title = title;
            post.Body = body;
            post.Approved = approved;
            post.Sticky = sticky;
            post.Closed = closed;
            post.ViewCount = viewCount;
            post.ReplyCount = replyCount;
            post.LastPostBy = lastPostBy;
            post.LastPostDate = lastPostDate;
            post.UpdatedDate = updatedDate;
            post.Active = active;
            return post;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PostID
        {
            get
            {
                return _PostID;
            }
            set
            {
                if (_PostID != value)
                {
                    OnPostIDChanging(value);
                    ReportPropertyChanging("PostID");
                    _PostID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PostID");
                    OnPostIDChanged();
                }
            }
        }
        private global::System.Int32 _PostID;
        partial void OnPostIDChanging(global::System.Int32 value);
        partial void OnPostIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AddedDate
        {
            get
            {
                return _AddedDate;
            }
            set
            {
                OnAddedDateChanging(value);
                ReportPropertyChanging("AddedDate");
                _AddedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedDate");
                OnAddedDateChanged();
            }
        }
        private global::System.DateTime _AddedDate;
        partial void OnAddedDateChanging(global::System.DateTime value);
        partial void OnAddedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddedBy
        {
            get
            {
                return _AddedBy;
            }
            set
            {
                OnAddedByChanging(value);
                ReportPropertyChanging("AddedBy");
                _AddedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AddedBy");
                OnAddedByChanged();
            }
        }
        private global::System.String _AddedBy;
        partial void OnAddedByChanging(global::System.String value);
        partial void OnAddedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddedByIP
        {
            get
            {
                return _AddedByIP;
            }
            set
            {
                OnAddedByIPChanging(value);
                ReportPropertyChanging("AddedByIP");
                _AddedByIP = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AddedByIP");
                OnAddedByIPChanged();
            }
        }
        private global::System.String _AddedByIP;
        partial void OnAddedByIPChanging(global::System.String value);
        partial void OnAddedByIPChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ParentPostID
        {
            get
            {
                return _ParentPostID;
            }
            set
            {
                OnParentPostIDChanging(value);
                ReportPropertyChanging("ParentPostID");
                _ParentPostID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentPostID");
                OnParentPostIDChanged();
            }
        }
        private global::System.Int32 _ParentPostID;
        partial void OnParentPostIDChanging(global::System.Int32 value);
        partial void OnParentPostIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Body
        {
            get
            {
                return _Body;
            }
            set
            {
                OnBodyChanging(value);
                ReportPropertyChanging("Body");
                _Body = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Body");
                OnBodyChanged();
            }
        }
        private global::System.String _Body;
        partial void OnBodyChanging(global::System.String value);
        partial void OnBodyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Approved
        {
            get
            {
                return _Approved;
            }
            set
            {
                OnApprovedChanging(value);
                ReportPropertyChanging("Approved");
                _Approved = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Approved");
                OnApprovedChanged();
            }
        }
        private global::System.Boolean _Approved;
        partial void OnApprovedChanging(global::System.Boolean value);
        partial void OnApprovedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Sticky
        {
            get
            {
                return _Sticky;
            }
            set
            {
                OnStickyChanging(value);
                ReportPropertyChanging("Sticky");
                _Sticky = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sticky");
                OnStickyChanged();
            }
        }
        private global::System.Boolean _Sticky;
        partial void OnStickyChanging(global::System.Boolean value);
        partial void OnStickyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Closed
        {
            get
            {
                return _Closed;
            }
            set
            {
                OnClosedChanging(value);
                ReportPropertyChanging("Closed");
                _Closed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Closed");
                OnClosedChanged();
            }
        }
        private global::System.Boolean _Closed;
        partial void OnClosedChanging(global::System.Boolean value);
        partial void OnClosedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ViewCount
        {
            get
            {
                return _ViewCount;
            }
            set
            {
                OnViewCountChanging(value);
                ReportPropertyChanging("ViewCount");
                _ViewCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ViewCount");
                OnViewCountChanged();
            }
        }
        private global::System.Int32 _ViewCount;
        partial void OnViewCountChanging(global::System.Int32 value);
        partial void OnViewCountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReplyCount
        {
            get
            {
                return _ReplyCount;
            }
            set
            {
                OnReplyCountChanging(value);
                ReportPropertyChanging("ReplyCount");
                _ReplyCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReplyCount");
                OnReplyCountChanged();
            }
        }
        private global::System.Int32 _ReplyCount;
        partial void OnReplyCountChanging(global::System.Int32 value);
        partial void OnReplyCountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastPostBy
        {
            get
            {
                return _LastPostBy;
            }
            set
            {
                OnLastPostByChanging(value);
                ReportPropertyChanging("LastPostBy");
                _LastPostBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastPostBy");
                OnLastPostByChanged();
            }
        }
        private global::System.String _LastPostBy;
        partial void OnLastPostByChanging(global::System.String value);
        partial void OnLastPostByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastPostDate
        {
            get
            {
                return _LastPostDate;
            }
            set
            {
                OnLastPostDateChanging(value);
                ReportPropertyChanging("LastPostDate");
                _LastPostDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastPostDate");
                OnLastPostDateChanged();
            }
        }
        private global::System.DateTime _LastPostDate;
        partial void OnLastPostDateChanging(global::System.DateTime value);
        partial void OnLastPostDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UpdatedDate
        {
            get
            {
                return _UpdatedDate;
            }
            set
            {
                OnUpdatedDateChanging(value);
                ReportPropertyChanging("UpdatedDate");
                _UpdatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedDate");
                OnUpdatedDateChanged();
            }
        }
        private global::System.DateTime _UpdatedDate;
        partial void OnUpdatedDateChanging(global::System.DateTime value);
        partial void OnUpdatedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private global::System.String _UpdatedBy;
        partial void OnUpdatedByChanging(global::System.String value);
        partial void OnUpdatedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BBICMS.Forums", "FK_tbh_Posts_tbh_Forums", "tbh_Forums")]
        public Forum Forum
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Forum>("BBICMS.Forums.FK_tbh_Posts_tbh_Forums", "tbh_Forums").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Forum>("BBICMS.Forums.FK_tbh_Posts_tbh_Forums", "tbh_Forums").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Forum> ForumReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Forum>("BBICMS.Forums.FK_tbh_Posts_tbh_Forums", "tbh_Forums");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Forum>("BBICMS.Forums.FK_tbh_Posts_tbh_Forums", "tbh_Forums", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
