//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("BBICMSPolling", "FK_tbh_PollOptions_tbh_Polls", "tbh_Polls", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BBICMS.Polls.Poll), "tbh_PollOptions", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BBICMS.Polls.PollOption))]

#endregion

namespace BBICMS.Polls
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class PollEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“PollEntities”部分中的连接字符串初始化新 PollEntities 对象。
        /// </summary>
        public PollEntities() : base("name=PollEntities", "PollEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 PollEntities 对象。
        /// </summary>
        public PollEntities(string connectionString) : base(connectionString, "PollEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 PollEntities 对象。
        /// </summary>
        public PollEntities(EntityConnection connection) : base(connection, "PollEntities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<PollOption> PollOptions
        {
            get
            {
                if ((_PollOptions == null))
                {
                    _PollOptions = base.CreateObjectSet<PollOption>("PollOptions");
                }
                return _PollOptions;
            }
        }
        private ObjectSet<PollOption> _PollOptions;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Poll> Polls
        {
            get
            {
                if ((_Polls == null))
                {
                    _Polls = base.CreateObjectSet<Poll>("Polls");
                }
                return _Polls;
            }
        }
        private ObjectSet<Poll> _Polls;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 PollOptions EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToPollOptions(PollOption pollOption)
        {
            base.AddObject("PollOptions", pollOption);
        }
    
        /// <summary>
        /// 用于向 Polls EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToPolls(Poll poll)
        {
            base.AddObject("Polls", poll);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BBICMSPolling", Name="Poll")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Poll : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Poll 对象。
        /// </summary>
        /// <param name="pollID">PollID 属性的初始值。</param>
        /// <param name="addedDate">AddedDate 属性的初始值。</param>
        /// <param name="addedBy">AddedBy 属性的初始值。</param>
        /// <param name="questionText">QuestionText 属性的初始值。</param>
        /// <param name="isCurrent">IsCurrent 属性的初始值。</param>
        /// <param name="isArchived">IsArchived 属性的初始值。</param>
        /// <param name="updatedDate">UpdatedDate 属性的初始值。</param>
        /// <param name="active">Active 属性的初始值。</param>
        public static Poll CreatePoll(global::System.Int32 pollID, global::System.DateTime addedDate, global::System.String addedBy, global::System.String questionText, global::System.Boolean isCurrent, global::System.Boolean isArchived, global::System.DateTime updatedDate, global::System.Boolean active)
        {
            Poll poll = new Poll();
            poll.PollID = pollID;
            poll.AddedDate = addedDate;
            poll.AddedBy = addedBy;
            poll.QuestionText = questionText;
            poll.IsCurrent = isCurrent;
            poll.IsArchived = isArchived;
            poll.UpdatedDate = updatedDate;
            poll.Active = active;
            return poll;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PollID
        {
            get
            {
                return _PollID;
            }
            set
            {
                if (_PollID != value)
                {
                    OnPollIDChanging(value);
                    ReportPropertyChanging("PollID");
                    _PollID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PollID");
                    OnPollIDChanged();
                }
            }
        }
        private global::System.Int32 _PollID;
        partial void OnPollIDChanging(global::System.Int32 value);
        partial void OnPollIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AddedDate
        {
            get
            {
                return _AddedDate;
            }
            set
            {
                OnAddedDateChanging(value);
                ReportPropertyChanging("AddedDate");
                _AddedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedDate");
                OnAddedDateChanged();
            }
        }
        private global::System.DateTime _AddedDate;
        partial void OnAddedDateChanging(global::System.DateTime value);
        partial void OnAddedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddedBy
        {
            get
            {
                return _AddedBy;
            }
            set
            {
                OnAddedByChanging(value);
                ReportPropertyChanging("AddedBy");
                _AddedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AddedBy");
                OnAddedByChanged();
            }
        }
        private global::System.String _AddedBy;
        partial void OnAddedByChanging(global::System.String value);
        partial void OnAddedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String QuestionText
        {
            get
            {
                return _QuestionText;
            }
            set
            {
                OnQuestionTextChanging(value);
                ReportPropertyChanging("QuestionText");
                _QuestionText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("QuestionText");
                OnQuestionTextChanged();
            }
        }
        private global::System.String _QuestionText;
        partial void OnQuestionTextChanging(global::System.String value);
        partial void OnQuestionTextChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsCurrent
        {
            get
            {
                return _IsCurrent;
            }
            set
            {
                OnIsCurrentChanging(value);
                ReportPropertyChanging("IsCurrent");
                _IsCurrent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsCurrent");
                OnIsCurrentChanged();
            }
        }
        private global::System.Boolean _IsCurrent;
        partial void OnIsCurrentChanging(global::System.Boolean value);
        partial void OnIsCurrentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsArchived
        {
            get
            {
                return _IsArchived;
            }
            set
            {
                OnIsArchivedChanging(value);
                ReportPropertyChanging("IsArchived");
                _IsArchived = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsArchived");
                OnIsArchivedChanged();
            }
        }
        private global::System.Boolean _IsArchived;
        partial void OnIsArchivedChanging(global::System.Boolean value);
        partial void OnIsArchivedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ArchivedDate
        {
            get
            {
                return _ArchivedDate;
            }
            set
            {
                OnArchivedDateChanging(value);
                ReportPropertyChanging("ArchivedDate");
                _ArchivedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ArchivedDate");
                OnArchivedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ArchivedDate;
        partial void OnArchivedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnArchivedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UpdatedDate
        {
            get
            {
                return _UpdatedDate;
            }
            set
            {
                OnUpdatedDateChanging(value);
                ReportPropertyChanging("UpdatedDate");
                _UpdatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedDate");
                OnUpdatedDateChanged();
            }
        }
        private global::System.DateTime _UpdatedDate;
        partial void OnUpdatedDateChanging(global::System.DateTime value);
        partial void OnUpdatedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private global::System.String _UpdatedBy;
        partial void OnUpdatedByChanging(global::System.String value);
        partial void OnUpdatedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BBICMSPolling", "FK_tbh_PollOptions_tbh_Polls", "tbh_PollOptions")]
        public EntityCollection<PollOption> PollOptions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PollOption>("BBICMSPolling.FK_tbh_PollOptions_tbh_Polls", "tbh_PollOptions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PollOption>("BBICMSPolling.FK_tbh_PollOptions_tbh_Polls", "tbh_PollOptions", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BBICMSPolling", Name="PollOption")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PollOption : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 PollOption 对象。
        /// </summary>
        /// <param name="optionID">OptionID 属性的初始值。</param>
        /// <param name="addedDate">AddedDate 属性的初始值。</param>
        /// <param name="addedBy">AddedBy 属性的初始值。</param>
        /// <param name="optionText">OptionText 属性的初始值。</param>
        /// <param name="votes">Votes 属性的初始值。</param>
        /// <param name="updatedDate">UpdatedDate 属性的初始值。</param>
        /// <param name="active">Active 属性的初始值。</param>
        public static PollOption CreatePollOption(global::System.Int32 optionID, global::System.DateTime addedDate, global::System.String addedBy, global::System.String optionText, global::System.Int32 votes, global::System.DateTime updatedDate, global::System.Boolean active)
        {
            PollOption pollOption = new PollOption();
            pollOption.OptionID = optionID;
            pollOption.AddedDate = addedDate;
            pollOption.AddedBy = addedBy;
            pollOption.OptionText = optionText;
            pollOption.Votes = votes;
            pollOption.UpdatedDate = updatedDate;
            pollOption.Active = active;
            return pollOption;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OptionID
        {
            get
            {
                return _OptionID;
            }
            set
            {
                if (_OptionID != value)
                {
                    OnOptionIDChanging(value);
                    ReportPropertyChanging("OptionID");
                    _OptionID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OptionID");
                    OnOptionIDChanged();
                }
            }
        }
        private global::System.Int32 _OptionID;
        partial void OnOptionIDChanging(global::System.Int32 value);
        partial void OnOptionIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AddedDate
        {
            get
            {
                return _AddedDate;
            }
            set
            {
                OnAddedDateChanging(value);
                ReportPropertyChanging("AddedDate");
                _AddedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedDate");
                OnAddedDateChanged();
            }
        }
        private global::System.DateTime _AddedDate;
        partial void OnAddedDateChanging(global::System.DateTime value);
        partial void OnAddedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddedBy
        {
            get
            {
                return _AddedBy;
            }
            set
            {
                OnAddedByChanging(value);
                ReportPropertyChanging("AddedBy");
                _AddedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AddedBy");
                OnAddedByChanged();
            }
        }
        private global::System.String _AddedBy;
        partial void OnAddedByChanging(global::System.String value);
        partial void OnAddedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OptionText
        {
            get
            {
                return _OptionText;
            }
            set
            {
                OnOptionTextChanging(value);
                ReportPropertyChanging("OptionText");
                _OptionText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OptionText");
                OnOptionTextChanged();
            }
        }
        private global::System.String _OptionText;
        partial void OnOptionTextChanging(global::System.String value);
        partial void OnOptionTextChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Votes
        {
            get
            {
                return _Votes;
            }
            set
            {
                OnVotesChanging(value);
                ReportPropertyChanging("Votes");
                _Votes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Votes");
                OnVotesChanged();
            }
        }
        private global::System.Int32 _Votes;
        partial void OnVotesChanging(global::System.Int32 value);
        partial void OnVotesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UpdatedDate
        {
            get
            {
                return _UpdatedDate;
            }
            set
            {
                OnUpdatedDateChanging(value);
                ReportPropertyChanging("UpdatedDate");
                _UpdatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedDate");
                OnUpdatedDateChanged();
            }
        }
        private global::System.DateTime _UpdatedDate;
        partial void OnUpdatedDateChanging(global::System.DateTime value);
        partial void OnUpdatedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private global::System.String _UpdatedBy;
        partial void OnUpdatedByChanging(global::System.String value);
        partial void OnUpdatedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BBICMSPolling", "FK_tbh_PollOptions_tbh_Polls", "tbh_Polls")]
        public Poll Poll
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Poll>("BBICMSPolling.FK_tbh_PollOptions_tbh_Polls", "tbh_Polls").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Poll>("BBICMSPolling.FK_tbh_PollOptions_tbh_Polls", "tbh_Polls").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Poll> PollReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Poll>("BBICMSPolling.FK_tbh_PollOptions_tbh_Polls", "tbh_Polls");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Poll>("BBICMSPolling.FK_tbh_PollOptions_tbh_Polls", "tbh_Polls", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
