//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("ShoppingCart", "FK_tbh_OrderItems_tbh_Orders", "tbh_Orders", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BBICMS.Store.Order), "tbh_OrderItems", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BBICMS.Store.OrderItem))]
[assembly: EdmRelationshipAttribute("ShoppingCart", "FK_tbh_Products_tbh_Departments", "tbh_Departments", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BBICMS.Store.Department), "tbh_Products", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BBICMS.Store.Product), true)]
[assembly: EdmRelationshipAttribute("ShoppingCart", "FK_store_Photos_tbh_Products", "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BBICMS.Store.Product), "store_Photos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BBICMS.Store.Photo), true)]

#endregion

namespace BBICMS.Store
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class ShoppingEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“ShoppingEntities”部分中的连接字符串初始化新 ShoppingEntities 对象。
        /// </summary>
        public ShoppingEntities() : base("name=ShoppingEntities", "ShoppingEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ShoppingEntities 对象。
        /// </summary>
        public ShoppingEntities(string connectionString) : base(connectionString, "ShoppingEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ShoppingEntities 对象。
        /// </summary>
        public ShoppingEntities(EntityConnection connection) : base(connection, "ShoppingEntities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<OrderItem> OrderItems
        {
            get
            {
                if ((_OrderItems == null))
                {
                    _OrderItems = base.CreateObjectSet<OrderItem>("OrderItems");
                }
                return _OrderItems;
            }
        }
        private ObjectSet<OrderItem> _OrderItems;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Order> Orders
        {
            get
            {
                if ((_Orders == null))
                {
                    _Orders = base.CreateObjectSet<Order>("Orders");
                }
                return _Orders;
            }
        }
        private ObjectSet<Order> _Orders;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<OrderStatus> OrderStatuses
        {
            get
            {
                if ((_OrderStatuses == null))
                {
                    _OrderStatuses = base.CreateObjectSet<OrderStatus>("OrderStatuses");
                }
                return _OrderStatuses;
            }
        }
        private ObjectSet<OrderStatus> _OrderStatuses;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<ShippingMethod> ShippingMethods
        {
            get
            {
                if ((_ShippingMethods == null))
                {
                    _ShippingMethods = base.CreateObjectSet<ShippingMethod>("ShippingMethods");
                }
                return _ShippingMethods;
            }
        }
        private ObjectSet<ShippingMethod> _ShippingMethods;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Department> Departments
        {
            get
            {
                if ((_Departments == null))
                {
                    _Departments = base.CreateObjectSet<Department>("Departments");
                }
                return _Departments;
            }
        }
        private ObjectSet<Department> _Departments;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Photo> Photos
        {
            get
            {
                if ((_Photos == null))
                {
                    _Photos = base.CreateObjectSet<Photo>("Photos");
                }
                return _Photos;
            }
        }
        private ObjectSet<Photo> _Photos;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 OrderItems EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToOrderItems(OrderItem orderItem)
        {
            base.AddObject("OrderItems", orderItem);
        }
    
        /// <summary>
        /// 用于向 Orders EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToOrders(Order order)
        {
            base.AddObject("Orders", order);
        }
    
        /// <summary>
        /// 用于向 OrderStatuses EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToOrderStatuses(OrderStatus orderStatus)
        {
            base.AddObject("OrderStatuses", orderStatus);
        }
    
        /// <summary>
        /// 用于向 ShippingMethods EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToShippingMethods(ShippingMethod shippingMethod)
        {
            base.AddObject("ShippingMethods", shippingMethod);
        }
    
        /// <summary>
        /// 用于向 Departments EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToDepartments(Department department)
        {
            base.AddObject("Departments", department);
        }
    
        /// <summary>
        /// 用于向 Products EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }
    
        /// <summary>
        /// 用于向 Photos EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToPhotos(Photo photo)
        {
            base.AddObject("Photos", photo);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ShoppingCart", Name="Department")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Department : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Department 对象。
        /// </summary>
        /// <param name="departmentID">DepartmentID 属性的初始值。</param>
        /// <param name="addedDate">AddedDate 属性的初始值。</param>
        /// <param name="addedBy">AddedBy 属性的初始值。</param>
        /// <param name="title">Title 属性的初始值。</param>
        /// <param name="importance">Importance 属性的初始值。</param>
        /// <param name="updatedDate">UpdatedDate 属性的初始值。</param>
        /// <param name="active">Active 属性的初始值。</param>
        public static Department CreateDepartment(global::System.Int32 departmentID, global::System.DateTime addedDate, global::System.String addedBy, global::System.String title, global::System.Int32 importance, global::System.DateTime updatedDate, global::System.Boolean active)
        {
            Department department = new Department();
            department.DepartmentID = departmentID;
            department.AddedDate = addedDate;
            department.AddedBy = addedBy;
            department.Title = title;
            department.Importance = importance;
            department.UpdatedDate = updatedDate;
            department.Active = active;
            return department;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DepartmentID
        {
            get
            {
                return _DepartmentID;
            }
            set
            {
                if (_DepartmentID != value)
                {
                    OnDepartmentIDChanging(value);
                    ReportPropertyChanging("DepartmentID");
                    _DepartmentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DepartmentID");
                    OnDepartmentIDChanged();
                }
            }
        }
        private global::System.Int32 _DepartmentID;
        partial void OnDepartmentIDChanging(global::System.Int32 value);
        partial void OnDepartmentIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AddedDate
        {
            get
            {
                return _AddedDate;
            }
            set
            {
                OnAddedDateChanging(value);
                ReportPropertyChanging("AddedDate");
                _AddedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedDate");
                OnAddedDateChanged();
            }
        }
        private global::System.DateTime _AddedDate;
        partial void OnAddedDateChanging(global::System.DateTime value);
        partial void OnAddedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddedBy
        {
            get
            {
                return _AddedBy;
            }
            set
            {
                OnAddedByChanging(value);
                ReportPropertyChanging("AddedBy");
                _AddedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AddedBy");
                OnAddedByChanged();
            }
        }
        private global::System.String _AddedBy;
        partial void OnAddedByChanging(global::System.String value);
        partial void OnAddedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Importance
        {
            get
            {
                return _Importance;
            }
            set
            {
                OnImportanceChanging(value);
                ReportPropertyChanging("Importance");
                _Importance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Importance");
                OnImportanceChanged();
            }
        }
        private global::System.Int32 _Importance;
        partial void OnImportanceChanging(global::System.Int32 value);
        partial void OnImportanceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImageUrl
        {
            get
            {
                return _ImageUrl;
            }
            set
            {
                OnImageUrlChanging(value);
                ReportPropertyChanging("ImageUrl");
                _ImageUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImageUrl");
                OnImageUrlChanged();
            }
        }
        private global::System.String _ImageUrl;
        partial void OnImageUrlChanging(global::System.String value);
        partial void OnImageUrlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UpdatedDate
        {
            get
            {
                return _UpdatedDate;
            }
            set
            {
                OnUpdatedDateChanging(value);
                ReportPropertyChanging("UpdatedDate");
                _UpdatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedDate");
                OnUpdatedDateChanged();
            }
        }
        private global::System.DateTime _UpdatedDate;
        partial void OnUpdatedDateChanging(global::System.DateTime value);
        partial void OnUpdatedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private global::System.String _UpdatedBy;
        partial void OnUpdatedByChanging(global::System.String value);
        partial void OnUpdatedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ShoppingCart", "FK_tbh_Products_tbh_Departments", "tbh_Products")]
        public EntityCollection<Product> Products
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Product>("ShoppingCart.FK_tbh_Products_tbh_Departments", "tbh_Products");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Product>("ShoppingCart.FK_tbh_Products_tbh_Departments", "tbh_Products", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ShoppingCart", Name="Order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Order : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Order 对象。
        /// </summary>
        /// <param name="orderID">OrderID 属性的初始值。</param>
        /// <param name="addedDate">AddedDate 属性的初始值。</param>
        /// <param name="addedBy">AddedBy 属性的初始值。</param>
        /// <param name="statusID">StatusID 属性的初始值。</param>
        /// <param name="shippingMethod">ShippingMethod 属性的初始值。</param>
        /// <param name="subTotal">SubTotal 属性的初始值。</param>
        /// <param name="shipping">Shipping 属性的初始值。</param>
        /// <param name="shippingFirstName">ShippingFirstName 属性的初始值。</param>
        /// <param name="shippingLastName">ShippingLastName 属性的初始值。</param>
        /// <param name="shippingStreet">ShippingStreet 属性的初始值。</param>
        /// <param name="shippingPostalCode">ShippingPostalCode 属性的初始值。</param>
        /// <param name="shippingCity">ShippingCity 属性的初始值。</param>
        /// <param name="shippingState">ShippingState 属性的初始值。</param>
        /// <param name="shippingCountry">ShippingCountry 属性的初始值。</param>
        /// <param name="customerEmail">CustomerEmail 属性的初始值。</param>
        /// <param name="customerPhone">CustomerPhone 属性的初始值。</param>
        /// <param name="customerFax">CustomerFax 属性的初始值。</param>
        /// <param name="updatedDate">UpdatedDate 属性的初始值。</param>
        /// <param name="active">Active 属性的初始值。</param>
        public static Order CreateOrder(global::System.Int32 orderID, global::System.DateTime addedDate, global::System.String addedBy, global::System.Int32 statusID, global::System.String shippingMethod, global::System.Decimal subTotal, global::System.Decimal shipping, global::System.String shippingFirstName, global::System.String shippingLastName, global::System.String shippingStreet, global::System.String shippingPostalCode, global::System.String shippingCity, global::System.String shippingState, global::System.String shippingCountry, global::System.String customerEmail, global::System.String customerPhone, global::System.String customerFax, global::System.DateTime updatedDate, global::System.Boolean active)
        {
            Order order = new Order();
            order.OrderID = orderID;
            order.AddedDate = addedDate;
            order.AddedBy = addedBy;
            order.StatusID = statusID;
            order.ShippingMethod = shippingMethod;
            order.SubTotal = subTotal;
            order.Shipping = shipping;
            order.ShippingFirstName = shippingFirstName;
            order.ShippingLastName = shippingLastName;
            order.ShippingStreet = shippingStreet;
            order.ShippingPostalCode = shippingPostalCode;
            order.ShippingCity = shippingCity;
            order.ShippingState = shippingState;
            order.ShippingCountry = shippingCountry;
            order.CustomerEmail = customerEmail;
            order.CustomerPhone = customerPhone;
            order.CustomerFax = customerFax;
            order.UpdatedDate = updatedDate;
            order.Active = active;
            return order;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderID
        {
            get
            {
                return _OrderID;
            }
            set
            {
                if (_OrderID != value)
                {
                    OnOrderIDChanging(value);
                    ReportPropertyChanging("OrderID");
                    _OrderID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderID");
                    OnOrderIDChanged();
                }
            }
        }
        private global::System.Int32 _OrderID;
        partial void OnOrderIDChanging(global::System.Int32 value);
        partial void OnOrderIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AddedDate
        {
            get
            {
                return _AddedDate;
            }
            set
            {
                OnAddedDateChanging(value);
                ReportPropertyChanging("AddedDate");
                _AddedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedDate");
                OnAddedDateChanged();
            }
        }
        private global::System.DateTime _AddedDate;
        partial void OnAddedDateChanging(global::System.DateTime value);
        partial void OnAddedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddedBy
        {
            get
            {
                return _AddedBy;
            }
            set
            {
                OnAddedByChanging(value);
                ReportPropertyChanging("AddedBy");
                _AddedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AddedBy");
                OnAddedByChanged();
            }
        }
        private global::System.String _AddedBy;
        partial void OnAddedByChanging(global::System.String value);
        partial void OnAddedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StatusID
        {
            get
            {
                return _StatusID;
            }
            set
            {
                OnStatusIDChanging(value);
                ReportPropertyChanging("StatusID");
                _StatusID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StatusID");
                OnStatusIDChanged();
            }
        }
        private global::System.Int32 _StatusID;
        partial void OnStatusIDChanging(global::System.Int32 value);
        partial void OnStatusIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ShippingMethod
        {
            get
            {
                return _ShippingMethod;
            }
            set
            {
                OnShippingMethodChanging(value);
                ReportPropertyChanging("ShippingMethod");
                _ShippingMethod = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ShippingMethod");
                OnShippingMethodChanged();
            }
        }
        private global::System.String _ShippingMethod;
        partial void OnShippingMethodChanging(global::System.String value);
        partial void OnShippingMethodChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal SubTotal
        {
            get
            {
                return _SubTotal;
            }
            set
            {
                OnSubTotalChanging(value);
                ReportPropertyChanging("SubTotal");
                _SubTotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SubTotal");
                OnSubTotalChanged();
            }
        }
        private global::System.Decimal _SubTotal;
        partial void OnSubTotalChanging(global::System.Decimal value);
        partial void OnSubTotalChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Shipping
        {
            get
            {
                return _Shipping;
            }
            set
            {
                OnShippingChanging(value);
                ReportPropertyChanging("Shipping");
                _Shipping = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Shipping");
                OnShippingChanged();
            }
        }
        private global::System.Decimal _Shipping;
        partial void OnShippingChanging(global::System.Decimal value);
        partial void OnShippingChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ShippingFirstName
        {
            get
            {
                return _ShippingFirstName;
            }
            set
            {
                OnShippingFirstNameChanging(value);
                ReportPropertyChanging("ShippingFirstName");
                _ShippingFirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ShippingFirstName");
                OnShippingFirstNameChanged();
            }
        }
        private global::System.String _ShippingFirstName;
        partial void OnShippingFirstNameChanging(global::System.String value);
        partial void OnShippingFirstNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ShippingLastName
        {
            get
            {
                return _ShippingLastName;
            }
            set
            {
                OnShippingLastNameChanging(value);
                ReportPropertyChanging("ShippingLastName");
                _ShippingLastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ShippingLastName");
                OnShippingLastNameChanged();
            }
        }
        private global::System.String _ShippingLastName;
        partial void OnShippingLastNameChanging(global::System.String value);
        partial void OnShippingLastNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ShippingStreet
        {
            get
            {
                return _ShippingStreet;
            }
            set
            {
                OnShippingStreetChanging(value);
                ReportPropertyChanging("ShippingStreet");
                _ShippingStreet = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ShippingStreet");
                OnShippingStreetChanged();
            }
        }
        private global::System.String _ShippingStreet;
        partial void OnShippingStreetChanging(global::System.String value);
        partial void OnShippingStreetChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ShippingPostalCode
        {
            get
            {
                return _ShippingPostalCode;
            }
            set
            {
                OnShippingPostalCodeChanging(value);
                ReportPropertyChanging("ShippingPostalCode");
                _ShippingPostalCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ShippingPostalCode");
                OnShippingPostalCodeChanged();
            }
        }
        private global::System.String _ShippingPostalCode;
        partial void OnShippingPostalCodeChanging(global::System.String value);
        partial void OnShippingPostalCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ShippingCity
        {
            get
            {
                return _ShippingCity;
            }
            set
            {
                OnShippingCityChanging(value);
                ReportPropertyChanging("ShippingCity");
                _ShippingCity = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ShippingCity");
                OnShippingCityChanged();
            }
        }
        private global::System.String _ShippingCity;
        partial void OnShippingCityChanging(global::System.String value);
        partial void OnShippingCityChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ShippingState
        {
            get
            {
                return _ShippingState;
            }
            set
            {
                OnShippingStateChanging(value);
                ReportPropertyChanging("ShippingState");
                _ShippingState = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ShippingState");
                OnShippingStateChanged();
            }
        }
        private global::System.String _ShippingState;
        partial void OnShippingStateChanging(global::System.String value);
        partial void OnShippingStateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ShippingCountry
        {
            get
            {
                return _ShippingCountry;
            }
            set
            {
                OnShippingCountryChanging(value);
                ReportPropertyChanging("ShippingCountry");
                _ShippingCountry = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ShippingCountry");
                OnShippingCountryChanged();
            }
        }
        private global::System.String _ShippingCountry;
        partial void OnShippingCountryChanging(global::System.String value);
        partial void OnShippingCountryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustomerEmail
        {
            get
            {
                return _CustomerEmail;
            }
            set
            {
                OnCustomerEmailChanging(value);
                ReportPropertyChanging("CustomerEmail");
                _CustomerEmail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CustomerEmail");
                OnCustomerEmailChanged();
            }
        }
        private global::System.String _CustomerEmail;
        partial void OnCustomerEmailChanging(global::System.String value);
        partial void OnCustomerEmailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustomerPhone
        {
            get
            {
                return _CustomerPhone;
            }
            set
            {
                OnCustomerPhoneChanging(value);
                ReportPropertyChanging("CustomerPhone");
                _CustomerPhone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CustomerPhone");
                OnCustomerPhoneChanged();
            }
        }
        private global::System.String _CustomerPhone;
        partial void OnCustomerPhoneChanging(global::System.String value);
        partial void OnCustomerPhoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustomerFax
        {
            get
            {
                return _CustomerFax;
            }
            set
            {
                OnCustomerFaxChanging(value);
                ReportPropertyChanging("CustomerFax");
                _CustomerFax = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CustomerFax");
                OnCustomerFaxChanged();
            }
        }
        private global::System.String _CustomerFax;
        partial void OnCustomerFaxChanging(global::System.String value);
        partial void OnCustomerFaxChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ShippedDate
        {
            get
            {
                return _ShippedDate;
            }
            set
            {
                OnShippedDateChanging(value);
                ReportPropertyChanging("ShippedDate");
                _ShippedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShippedDate");
                OnShippedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ShippedDate;
        partial void OnShippedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnShippedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TransactionID
        {
            get
            {
                return _TransactionID;
            }
            set
            {
                OnTransactionIDChanging(value);
                ReportPropertyChanging("TransactionID");
                _TransactionID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TransactionID");
                OnTransactionIDChanged();
            }
        }
        private global::System.String _TransactionID;
        partial void OnTransactionIDChanging(global::System.String value);
        partial void OnTransactionIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TrackingID
        {
            get
            {
                return _TrackingID;
            }
            set
            {
                OnTrackingIDChanging(value);
                ReportPropertyChanging("TrackingID");
                _TrackingID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TrackingID");
                OnTrackingIDChanged();
            }
        }
        private global::System.String _TrackingID;
        partial void OnTrackingIDChanging(global::System.String value);
        partial void OnTrackingIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UpdatedDate
        {
            get
            {
                return _UpdatedDate;
            }
            set
            {
                OnUpdatedDateChanging(value);
                ReportPropertyChanging("UpdatedDate");
                _UpdatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedDate");
                OnUpdatedDateChanged();
            }
        }
        private global::System.DateTime _UpdatedDate;
        partial void OnUpdatedDateChanging(global::System.DateTime value);
        partial void OnUpdatedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private global::System.String _UpdatedBy;
        partial void OnUpdatedByChanging(global::System.String value);
        partial void OnUpdatedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ShoppingCart", "FK_tbh_OrderItems_tbh_Orders", "tbh_OrderItems")]
        public EntityCollection<OrderItem> OrderItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OrderItem>("ShoppingCart.FK_tbh_OrderItems_tbh_Orders", "tbh_OrderItems");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OrderItem>("ShoppingCart.FK_tbh_OrderItems_tbh_Orders", "tbh_OrderItems", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ShoppingCart", Name="OrderItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderItem : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 OrderItem 对象。
        /// </summary>
        /// <param name="orderItemID">OrderItemID 属性的初始值。</param>
        /// <param name="addedDate">AddedDate 属性的初始值。</param>
        /// <param name="addedBy">AddedBy 属性的初始值。</param>
        /// <param name="productID">ProductID 属性的初始值。</param>
        /// <param name="title">Title 属性的初始值。</param>
        /// <param name="sKU">SKU 属性的初始值。</param>
        /// <param name="unitPrice">UnitPrice 属性的初始值。</param>
        /// <param name="quantity">Quantity 属性的初始值。</param>
        /// <param name="updatedDate">UpdatedDate 属性的初始值。</param>
        public static OrderItem CreateOrderItem(global::System.Int32 orderItemID, global::System.DateTime addedDate, global::System.String addedBy, global::System.Int32 productID, global::System.String title, global::System.String sKU, global::System.Decimal unitPrice, global::System.Int32 quantity, global::System.DateTime updatedDate)
        {
            OrderItem orderItem = new OrderItem();
            orderItem.OrderItemID = orderItemID;
            orderItem.AddedDate = addedDate;
            orderItem.AddedBy = addedBy;
            orderItem.ProductID = productID;
            orderItem.Title = title;
            orderItem.SKU = sKU;
            orderItem.UnitPrice = unitPrice;
            orderItem.Quantity = quantity;
            orderItem.UpdatedDate = updatedDate;
            return orderItem;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderItemID
        {
            get
            {
                return _OrderItemID;
            }
            set
            {
                if (_OrderItemID != value)
                {
                    OnOrderItemIDChanging(value);
                    ReportPropertyChanging("OrderItemID");
                    _OrderItemID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderItemID");
                    OnOrderItemIDChanged();
                }
            }
        }
        private global::System.Int32 _OrderItemID;
        partial void OnOrderItemIDChanging(global::System.Int32 value);
        partial void OnOrderItemIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AddedDate
        {
            get
            {
                return _AddedDate;
            }
            set
            {
                OnAddedDateChanging(value);
                ReportPropertyChanging("AddedDate");
                _AddedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedDate");
                OnAddedDateChanged();
            }
        }
        private global::System.DateTime _AddedDate;
        partial void OnAddedDateChanging(global::System.DateTime value);
        partial void OnAddedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddedBy
        {
            get
            {
                return _AddedBy;
            }
            set
            {
                OnAddedByChanging(value);
                ReportPropertyChanging("AddedBy");
                _AddedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AddedBy");
                OnAddedByChanged();
            }
        }
        private global::System.String _AddedBy;
        partial void OnAddedByChanging(global::System.String value);
        partial void OnAddedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                OnProductIDChanging(value);
                ReportPropertyChanging("ProductID");
                _ProductID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductID");
                OnProductIDChanged();
            }
        }
        private global::System.Int32 _ProductID;
        partial void OnProductIDChanging(global::System.Int32 value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SKU
        {
            get
            {
                return _SKU;
            }
            set
            {
                OnSKUChanging(value);
                ReportPropertyChanging("SKU");
                _SKU = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SKU");
                OnSKUChanged();
            }
        }
        private global::System.String _SKU;
        partial void OnSKUChanging(global::System.String value);
        partial void OnSKUChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal UnitPrice
        {
            get
            {
                return _UnitPrice;
            }
            set
            {
                OnUnitPriceChanging(value);
                ReportPropertyChanging("UnitPrice");
                _UnitPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitPrice");
                OnUnitPriceChanged();
            }
        }
        private global::System.Decimal _UnitPrice;
        partial void OnUnitPriceChanging(global::System.Decimal value);
        partial void OnUnitPriceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private global::System.Int32 _Quantity;
        partial void OnQuantityChanging(global::System.Int32 value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UpdatedDate
        {
            get
            {
                return _UpdatedDate;
            }
            set
            {
                OnUpdatedDateChanging(value);
                ReportPropertyChanging("UpdatedDate");
                _UpdatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedDate");
                OnUpdatedDateChanged();
            }
        }
        private global::System.DateTime _UpdatedDate;
        partial void OnUpdatedDateChanging(global::System.DateTime value);
        partial void OnUpdatedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private global::System.String _UpdatedBy;
        partial void OnUpdatedByChanging(global::System.String value);
        partial void OnUpdatedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active = true;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ShoppingCart", "FK_tbh_OrderItems_tbh_Orders", "tbh_Orders")]
        public Order Order
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("ShoppingCart.FK_tbh_OrderItems_tbh_Orders", "tbh_Orders").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("ShoppingCart.FK_tbh_OrderItems_tbh_Orders", "tbh_Orders").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Order> OrderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("ShoppingCart.FK_tbh_OrderItems_tbh_Orders", "tbh_Orders");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Order>("ShoppingCart.FK_tbh_OrderItems_tbh_Orders", "tbh_Orders", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ShoppingCart", Name="OrderStatus")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OrderStatus : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 OrderStatus 对象。
        /// </summary>
        /// <param name="orderStatusID">OrderStatusID 属性的初始值。</param>
        /// <param name="addedDate">AddedDate 属性的初始值。</param>
        /// <param name="addedBy">AddedBy 属性的初始值。</param>
        /// <param name="title">Title 属性的初始值。</param>
        /// <param name="updatedDate">UpdatedDate 属性的初始值。</param>
        /// <param name="active">Active 属性的初始值。</param>
        public static OrderStatus CreateOrderStatus(global::System.Int32 orderStatusID, global::System.DateTime addedDate, global::System.String addedBy, global::System.String title, global::System.DateTime updatedDate, global::System.Boolean active)
        {
            OrderStatus orderStatus = new OrderStatus();
            orderStatus.OrderStatusID = orderStatusID;
            orderStatus.AddedDate = addedDate;
            orderStatus.AddedBy = addedBy;
            orderStatus.Title = title;
            orderStatus.UpdatedDate = updatedDate;
            orderStatus.Active = active;
            return orderStatus;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderStatusID
        {
            get
            {
                return _OrderStatusID;
            }
            set
            {
                if (_OrderStatusID != value)
                {
                    OnOrderStatusIDChanging(value);
                    ReportPropertyChanging("OrderStatusID");
                    _OrderStatusID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderStatusID");
                    OnOrderStatusIDChanged();
                }
            }
        }
        private global::System.Int32 _OrderStatusID;
        partial void OnOrderStatusIDChanging(global::System.Int32 value);
        partial void OnOrderStatusIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AddedDate
        {
            get
            {
                return _AddedDate;
            }
            set
            {
                OnAddedDateChanging(value);
                ReportPropertyChanging("AddedDate");
                _AddedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedDate");
                OnAddedDateChanged();
            }
        }
        private global::System.DateTime _AddedDate;
        partial void OnAddedDateChanging(global::System.DateTime value);
        partial void OnAddedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddedBy
        {
            get
            {
                return _AddedBy;
            }
            set
            {
                OnAddedByChanging(value);
                ReportPropertyChanging("AddedBy");
                _AddedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AddedBy");
                OnAddedByChanged();
            }
        }
        private global::System.String _AddedBy;
        partial void OnAddedByChanging(global::System.String value);
        partial void OnAddedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UpdatedDate
        {
            get
            {
                return _UpdatedDate;
            }
            set
            {
                OnUpdatedDateChanging(value);
                ReportPropertyChanging("UpdatedDate");
                _UpdatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedDate");
                OnUpdatedDateChanged();
            }
        }
        private global::System.DateTime _UpdatedDate;
        partial void OnUpdatedDateChanging(global::System.DateTime value);
        partial void OnUpdatedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private global::System.String _UpdatedBy;
        partial void OnUpdatedByChanging(global::System.String value);
        partial void OnUpdatedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ShoppingCart", Name="Photo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Photo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Photo 对象。
        /// </summary>
        /// <param name="photoID">PhotoID 属性的初始值。</param>
        /// <param name="productID">ProductID 属性的初始值。</param>
        /// <param name="addedBy">AddedBy 属性的初始值。</param>
        /// <param name="addedDate">AddedDate 属性的初始值。</param>
        /// <param name="thumbnail">Thumbnail 属性的初始值。</param>
        /// <param name="originalPic">OriginalPic 属性的初始值。</param>
        public static Photo CreatePhoto(global::System.Int32 photoID, global::System.Int32 productID, global::System.String addedBy, global::System.DateTime addedDate, global::System.String thumbnail, global::System.String originalPic)
        {
            Photo photo = new Photo();
            photo.PhotoID = photoID;
            photo.ProductID = productID;
            photo.AddedBy = addedBy;
            photo.AddedDate = addedDate;
            photo.Thumbnail = thumbnail;
            photo.OriginalPic = originalPic;
            return photo;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PhotoID
        {
            get
            {
                return _PhotoID;
            }
            set
            {
                if (_PhotoID != value)
                {
                    OnPhotoIDChanging(value);
                    ReportPropertyChanging("PhotoID");
                    _PhotoID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PhotoID");
                    OnPhotoIDChanged();
                }
            }
        }
        private global::System.Int32 _PhotoID;
        partial void OnPhotoIDChanging(global::System.Int32 value);
        partial void OnPhotoIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                OnProductIDChanging(value);
                ReportPropertyChanging("ProductID");
                _ProductID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductID");
                OnProductIDChanged();
            }
        }
        private global::System.Int32 _ProductID;
        partial void OnProductIDChanging(global::System.Int32 value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddedBy
        {
            get
            {
                return _AddedBy;
            }
            set
            {
                OnAddedByChanging(value);
                ReportPropertyChanging("AddedBy");
                _AddedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AddedBy");
                OnAddedByChanged();
            }
        }
        private global::System.String _AddedBy;
        partial void OnAddedByChanging(global::System.String value);
        partial void OnAddedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AddedDate
        {
            get
            {
                return _AddedDate;
            }
            set
            {
                OnAddedDateChanging(value);
                ReportPropertyChanging("AddedDate");
                _AddedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedDate");
                OnAddedDateChanged();
            }
        }
        private global::System.DateTime _AddedDate;
        partial void OnAddedDateChanging(global::System.DateTime value);
        partial void OnAddedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Thumbnail
        {
            get
            {
                return _Thumbnail;
            }
            set
            {
                OnThumbnailChanging(value);
                ReportPropertyChanging("Thumbnail");
                _Thumbnail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Thumbnail");
                OnThumbnailChanged();
            }
        }
        private global::System.String _Thumbnail;
        partial void OnThumbnailChanging(global::System.String value);
        partial void OnThumbnailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OriginalPic
        {
            get
            {
                return _OriginalPic;
            }
            set
            {
                OnOriginalPicChanging(value);
                ReportPropertyChanging("OriginalPic");
                _OriginalPic = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OriginalPic");
                OnOriginalPicChanged();
            }
        }
        private global::System.String _OriginalPic;
        partial void OnOriginalPicChanging(global::System.String value);
        partial void OnOriginalPicChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ShoppingCart", "FK_store_Photos_tbh_Products", "Product")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("ShoppingCart.FK_store_Photos_tbh_Products", "Product").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("ShoppingCart.FK_store_Photos_tbh_Products", "Product").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("ShoppingCart.FK_store_Photos_tbh_Products", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("ShoppingCart.FK_store_Photos_tbh_Products", "Product", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ShoppingCart", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Product 对象。
        /// </summary>
        /// <param name="productID">ProductID 属性的初始值。</param>
        /// <param name="addedDate">AddedDate 属性的初始值。</param>
        /// <param name="addedBy">AddedBy 属性的初始值。</param>
        /// <param name="departmentID">DepartmentID 属性的初始值。</param>
        /// <param name="title">Title 属性的初始值。</param>
        /// <param name="description">Description 属性的初始值。</param>
        /// <param name="sKU">SKU 属性的初始值。</param>
        /// <param name="unitPrice">UnitPrice 属性的初始值。</param>
        /// <param name="discountPercentage">DiscountPercentage 属性的初始值。</param>
        /// <param name="unitsInStock">UnitsInStock 属性的初始值。</param>
        /// <param name="votes">Votes 属性的初始值。</param>
        /// <param name="totalRating">TotalRating 属性的初始值。</param>
        /// <param name="updatedDate">UpdatedDate 属性的初始值。</param>
        /// <param name="active">Active 属性的初始值。</param>
        public static Product CreateProduct(global::System.Int32 productID, global::System.DateTime addedDate, global::System.String addedBy, global::System.Int32 departmentID, global::System.String title, global::System.String description, global::System.String sKU, global::System.Decimal unitPrice, global::System.Int32 discountPercentage, global::System.Int32 unitsInStock, global::System.Int32 votes, global::System.Int32 totalRating, global::System.DateTime updatedDate, global::System.Boolean active)
        {
            Product product = new Product();
            product.ProductID = productID;
            product.AddedDate = addedDate;
            product.AddedBy = addedBy;
            product.DepartmentID = departmentID;
            product.Title = title;
            product.Description = description;
            product.SKU = sKU;
            product.UnitPrice = unitPrice;
            product.DiscountPercentage = discountPercentage;
            product.UnitsInStock = unitsInStock;
            product.Votes = votes;
            product.TotalRating = totalRating;
            product.UpdatedDate = updatedDate;
            product.Active = active;
            return product;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                if (_ProductID != value)
                {
                    OnProductIDChanging(value);
                    ReportPropertyChanging("ProductID");
                    _ProductID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProductID");
                    OnProductIDChanged();
                }
            }
        }
        private global::System.Int32 _ProductID;
        partial void OnProductIDChanging(global::System.Int32 value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AddedDate
        {
            get
            {
                return _AddedDate;
            }
            set
            {
                OnAddedDateChanging(value);
                ReportPropertyChanging("AddedDate");
                _AddedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedDate");
                OnAddedDateChanged();
            }
        }
        private global::System.DateTime _AddedDate;
        partial void OnAddedDateChanging(global::System.DateTime value);
        partial void OnAddedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddedBy
        {
            get
            {
                return _AddedBy;
            }
            set
            {
                OnAddedByChanging(value);
                ReportPropertyChanging("AddedBy");
                _AddedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AddedBy");
                OnAddedByChanged();
            }
        }
        private global::System.String _AddedBy;
        partial void OnAddedByChanging(global::System.String value);
        partial void OnAddedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DepartmentID
        {
            get
            {
                return _DepartmentID;
            }
            set
            {
                OnDepartmentIDChanging(value);
                ReportPropertyChanging("DepartmentID");
                _DepartmentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DepartmentID");
                OnDepartmentIDChanged();
            }
        }
        private global::System.Int32 _DepartmentID;
        partial void OnDepartmentIDChanging(global::System.Int32 value);
        partial void OnDepartmentIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SKU
        {
            get
            {
                return _SKU;
            }
            set
            {
                OnSKUChanging(value);
                ReportPropertyChanging("SKU");
                _SKU = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SKU");
                OnSKUChanged();
            }
        }
        private global::System.String _SKU;
        partial void OnSKUChanging(global::System.String value);
        partial void OnSKUChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal UnitPrice
        {
            get
            {
                return _UnitPrice;
            }
            set
            {
                OnUnitPriceChanging(value);
                ReportPropertyChanging("UnitPrice");
                _UnitPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitPrice");
                OnUnitPriceChanged();
            }
        }
        private global::System.Decimal _UnitPrice;
        partial void OnUnitPriceChanging(global::System.Decimal value);
        partial void OnUnitPriceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DiscountPercentage
        {
            get
            {
                return _DiscountPercentage;
            }
            set
            {
                OnDiscountPercentageChanging(value);
                ReportPropertyChanging("DiscountPercentage");
                _DiscountPercentage = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DiscountPercentage");
                OnDiscountPercentageChanged();
            }
        }
        private global::System.Int32 _DiscountPercentage;
        partial void OnDiscountPercentageChanging(global::System.Int32 value);
        partial void OnDiscountPercentageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UnitsInStock
        {
            get
            {
                return _UnitsInStock;
            }
            set
            {
                OnUnitsInStockChanging(value);
                ReportPropertyChanging("UnitsInStock");
                _UnitsInStock = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitsInStock");
                OnUnitsInStockChanged();
            }
        }
        private global::System.Int32 _UnitsInStock;
        partial void OnUnitsInStockChanging(global::System.Int32 value);
        partial void OnUnitsInStockChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SmallImageUrl
        {
            get
            {
                return _SmallImageUrl;
            }
            set
            {
                OnSmallImageUrlChanging(value);
                ReportPropertyChanging("SmallImageUrl");
                _SmallImageUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SmallImageUrl");
                OnSmallImageUrlChanged();
            }
        }
        private global::System.String _SmallImageUrl;
        partial void OnSmallImageUrlChanging(global::System.String value);
        partial void OnSmallImageUrlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FullImageUrl
        {
            get
            {
                return _FullImageUrl;
            }
            set
            {
                OnFullImageUrlChanging(value);
                ReportPropertyChanging("FullImageUrl");
                _FullImageUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FullImageUrl");
                OnFullImageUrlChanged();
            }
        }
        private global::System.String _FullImageUrl;
        partial void OnFullImageUrlChanging(global::System.String value);
        partial void OnFullImageUrlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Votes
        {
            get
            {
                return _Votes;
            }
            set
            {
                OnVotesChanging(value);
                ReportPropertyChanging("Votes");
                _Votes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Votes");
                OnVotesChanged();
            }
        }
        private global::System.Int32 _Votes;
        partial void OnVotesChanging(global::System.Int32 value);
        partial void OnVotesChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TotalRating
        {
            get
            {
                return _TotalRating;
            }
            set
            {
                OnTotalRatingChanging(value);
                ReportPropertyChanging("TotalRating");
                _TotalRating = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalRating");
                OnTotalRatingChanged();
            }
        }
        private global::System.Int32 _TotalRating;
        partial void OnTotalRatingChanging(global::System.Int32 value);
        partial void OnTotalRatingChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UpdatedDate
        {
            get
            {
                return _UpdatedDate;
            }
            set
            {
                OnUpdatedDateChanging(value);
                ReportPropertyChanging("UpdatedDate");
                _UpdatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedDate");
                OnUpdatedDateChanged();
            }
        }
        private global::System.DateTime _UpdatedDate;
        partial void OnUpdatedDateChanging(global::System.DateTime value);
        partial void OnUpdatedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private global::System.String _UpdatedBy;
        partial void OnUpdatedByChanging(global::System.String value);
        partial void OnUpdatedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();

        #endregion

    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ShoppingCart", "FK_tbh_Products_tbh_Departments", "tbh_Departments")]
        public Department Department
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("ShoppingCart.FK_tbh_Products_tbh_Departments", "tbh_Departments").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("ShoppingCart.FK_tbh_Products_tbh_Departments", "tbh_Departments").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Department> DepartmentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Department>("ShoppingCart.FK_tbh_Products_tbh_Departments", "tbh_Departments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Department>("ShoppingCart.FK_tbh_Products_tbh_Departments", "tbh_Departments", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ShoppingCart", "FK_store_Photos_tbh_Products", "store_Photos")]
        public EntityCollection<Photo> Photos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Photo>("ShoppingCart.FK_store_Photos_tbh_Products", "store_Photos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Photo>("ShoppingCart.FK_store_Photos_tbh_Products", "store_Photos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ShoppingCart", Name="ShippingMethod")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ShippingMethod : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 ShippingMethod 对象。
        /// </summary>
        /// <param name="shippingMethodID">ShippingMethodID 属性的初始值。</param>
        /// <param name="addedDate">AddedDate 属性的初始值。</param>
        /// <param name="addedBy">AddedBy 属性的初始值。</param>
        /// <param name="title">Title 属性的初始值。</param>
        /// <param name="price">Price 属性的初始值。</param>
        /// <param name="updatedDate">UpdatedDate 属性的初始值。</param>
        /// <param name="active">Active 属性的初始值。</param>
        public static ShippingMethod CreateShippingMethod(global::System.Int32 shippingMethodID, global::System.DateTime addedDate, global::System.String addedBy, global::System.String title, global::System.Decimal price, global::System.DateTime updatedDate, global::System.Boolean active)
        {
            ShippingMethod shippingMethod = new ShippingMethod();
            shippingMethod.ShippingMethodID = shippingMethodID;
            shippingMethod.AddedDate = addedDate;
            shippingMethod.AddedBy = addedBy;
            shippingMethod.Title = title;
            shippingMethod.Price = price;
            shippingMethod.UpdatedDate = updatedDate;
            shippingMethod.Active = active;
            return shippingMethod;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ShippingMethodID
        {
            get
            {
                return _ShippingMethodID;
            }
            set
            {
                if (_ShippingMethodID != value)
                {
                    OnShippingMethodIDChanging(value);
                    ReportPropertyChanging("ShippingMethodID");
                    _ShippingMethodID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ShippingMethodID");
                    OnShippingMethodIDChanged();
                }
            }
        }
        private global::System.Int32 _ShippingMethodID;
        partial void OnShippingMethodIDChanging(global::System.Int32 value);
        partial void OnShippingMethodIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AddedDate
        {
            get
            {
                return _AddedDate;
            }
            set
            {
                OnAddedDateChanging(value);
                ReportPropertyChanging("AddedDate");
                _AddedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddedDate");
                OnAddedDateChanged();
            }
        }
        private global::System.DateTime _AddedDate;
        partial void OnAddedDateChanging(global::System.DateTime value);
        partial void OnAddedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddedBy
        {
            get
            {
                return _AddedBy;
            }
            set
            {
                OnAddedByChanging(value);
                ReportPropertyChanging("AddedBy");
                _AddedBy = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AddedBy");
                OnAddedByChanged();
            }
        }
        private global::System.String _AddedBy;
        partial void OnAddedByChanging(global::System.String value);
        partial void OnAddedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.Decimal _Price;
        partial void OnPriceChanging(global::System.Decimal value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UpdatedDate
        {
            get
            {
                return _UpdatedDate;
            }
            set
            {
                OnUpdatedDateChanging(value);
                ReportPropertyChanging("UpdatedDate");
                _UpdatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdatedDate");
                OnUpdatedDateChanged();
            }
        }
        private global::System.DateTime _UpdatedDate;
        partial void OnUpdatedDateChanging(global::System.DateTime value);
        partial void OnUpdatedDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UpdatedBy
        {
            get
            {
                return _UpdatedBy;
            }
            set
            {
                OnUpdatedByChanging(value);
                ReportPropertyChanging("UpdatedBy");
                _UpdatedBy = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UpdatedBy");
                OnUpdatedByChanged();
            }
        }
        private global::System.String _UpdatedBy;
        partial void OnUpdatedByChanging(global::System.String value);
        partial void OnUpdatedByChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();

        #endregion

    
    }

    #endregion

    
}
